#!name=Spotify_Pre_HuuD v1.0
#!desc=Mở khóa một phần premium, khuyến nghị đăng nhập lại, không thể thiết lập chất lượng âm thanh cao cấp

# By DHuu
[MITM]
hostname = %APPEND% spclient.wg.spotify.com

[Script]
spotify-proto = type=http-response,pattern=^https:\/\/spclient\.wg\.spotify\.com\/(bootstrap\/v1\/bootstrap|user-customization-service\/v1\/customize)$,requires-body=1,binary-body-mode=1,max-size=0,script-path=https://raw.githubusercontent.com/huud0905/App-Crack-Shadowrocket/refs/heads/main/js/Spotify/Spotify.js,script-update-interval=0
