#!name=Locket_Gold_HuuD v2.0
#!desc=Bật Locket Premium - Bản 2.0, ngày 02/01/2025, không quảng cáo, full tính năng

[Script]
# Xóa các header cache để server luôn trả về dữ liệu mới
deleteHeader = type=http-request,pattern=^https:\/\/api\.revenuecat\.com\/.+\/(receipts|subscribers),script-path=https://raw.githubusercontent.com/huud0905/App-Crack-Shadowrocket/refs/heads/main/js/v2.0/Locket/deleteHeader.js,timeout=60

# Inject Premium vào response RevenueCat cho Locket
revenuecat = type=http-response,pattern=^https:\/\/api\.revenuecat\.com\/.+\/(receipts$|subscribers\/[^/]+$),requires-body=true,script-path=https://raw.githubusercontent.com/huud0905/App-Crack-Shadowrocket/refs/heads/main/js/v2.0/Locket/Locket.js,timeout=60

[MITM]
# Bắt request đến RevenueCat để script hoạt động
hostname = %APPEND% api.revenuecat.com
